# Allow root access for priviledged users
privileged: true

image:
  file: gitpod/dockerimages/devuan/devuan.Dockerfile

tasks:
# NOTICE(Krey): Stub for root access
- command: [ "$(curl https://api.github.com/repos/gitpod-io/gitpod/issues/39 2>/dev/null | jq -r '.state')" = open ] && printf '\033[31m\033[1mBLOCKED:\033[0m %s\n' "Zernit development requires a root account for various system configuration and VM handling of cross-platform development which is provided only to privileged users (Gitpod Developers), see https://github.com/gitpod-io/gitpod/issues/39"
# NOTICE(Krey): Stub for VM support
- command: [ "$(curl https://api.github.com/repos/gitpod-io/gitpod/issues/1265 2>/dev/null | jq -r '.state')" = open ] && printf '\033[31m\033[1mBLOCKED:\033[0m %s\n' "Zernit development requires a VM support for cross-platforming which is currently not supported in gitpod, see https://github.com/gitpod-io/gitpod/issues/1265"

vscode:
  extensions:
    - kalitaalexey.vscode-rust@0.4.2:iw09QffwKU6Xcxr7C2zalA==
    - Swellaby.vscode-rust-test-adapter@0.11.0:Xg+YeZZQiVpVUsIkH+uiiw==
    - bungcip.better-toml@0.3.2:3QfgGxxYtGHfJKQU7H0nEw==
    - hbenl.vscode-test-explorer@2.15.0:koqDUMWDPJzELp/hdS/lWw==
    - belfz.search-crates-io@1.2.1:kSLnyrOhXtYPjQpKnMr4eQ==
    - serayuzgur.crates@0.4.7:HMkoguLcXp9M3ud7ac3eIw==
    - timonwong.shellcheck@0.9.0:hsU/Rd39aqPYowTqL+DbXg==
    - krosf.vscode-valgrind@0.0.1:YTn5lOY8OnPKJYDqJPr/Sg==
    - matklad.rust-analyzer@0.1.20200217:zozmBmOg1N91pRISIsYXBg==
    - exiasr.hadolint@0.3.0:/FkAW3eTb+z9O7VZAyAa0w==
    - DavidAnson.vscode-markdownlint@0.34.0:l4DL7iPpo7DdhfUHIUtcuQ==
    - yzhang.markdown-all-in-one@2.7.0:5+DmuGcePw8L9PtfgOAAHg==
